#### Consider the following list a, convert it to Numpy Array.

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [2]:
import numpy as np

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Calculate the numpy array size.

In [3]:
A.size

12

#### Access the element on the first row and first and second columns.

In [4]:
A[0][0:2]

array([1, 2])

#### Perform matrix multiplication with the numpy arrays A and B.

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

In [6]:
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
X = np.dot(A,B)
X

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])